# Updated : 2024.12.23
# Version : 1.2.5
# GitHub  : https://github.com/SeByDocKy/pvbrain2

substitutions:
  board_chip: "ESP32-S3"
  board_name: "PVbrain2"

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB # ajust according to your ESP32-S3 version
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio             # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing
    board_upload.maximum_ram_size: 524288   # total size of the internal RAM in bits, it's the same for all ESP32-S3 ( 512KB )

# PSRAM activation and settings
psram:
  mode: octal
  speed: 80MHz

# <<: !include board_psram_settings.yaml

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  ap:
    ssid: "YamBMS Fallback Hotspot"
    password: "Y4mBM$85"

captive_portal:

logger:
  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"
  hardware_uart: UART0 # UART0 / USB_SERIAL_JTAG

light:
  # https://esphome.io/components/light/status_led
  - platform: status_led
    name: ${name}_led_light_1
    id: led_light_1
    pin: GPIO01
    entity_category: config

  - platform: status_led
    name: ${name}_led_light_2
    id: led_light_2
    pin: GPIO02    
    entity_category: config

  # https://esphome.io/components/light/esp32_rmt_led_strip
  - platform: esp32_rmt_led_strip
    name: ${name}_on_board_light_io48
    id: on_board_light_io48
    rgb_order: GRB
    pin: GPIO48
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    entity_category: config
